spring.application.name=TranspoGov


server.port=4000

spring.datasource.url=jdbc:mysql://localhost:3306/transpo_gov
spring.datasource.username=root
spring.datasource.password=123213Abhi@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format-sql=true;
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


jwt.secret=dfg3rcvb32fghjk34fghj42eden43grhj

# Allow endpoints actuators 
management.endpoints.web.exposure.include=*

# log path
logging.file.name=logs/app.log
logging.file.path=logs