spring.application.name=TranspoGov


server.port=4001

spring.datasource.url=jdbc:mysql://localhost:3306/transpo_gov
spring.datasource.username=root
spring.datasource.password=Root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format-sql=true;
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Allow endpoints actuators 
management.endpoints.web.exposure.include=*